export const ICONS = {
  // Navigation
  dashboard: 'LayoutDashboard',
  sale:      'ShoppingCart',
  inventory: 'Package',
  customers: 'Users',
  history:   'ClipboardList',
  analytics: 'BarChart2',
  settings:  'Settings',

  // Actions
  add:       'Plus',
  edit:      'Pencil',
  delete:    'Trash2',
  archive:   'Archive',
  restore:   'ArchiveRestore',
  save:      'Check',
  cancel:    'X',
  close:     'X',
  search:    'Search',
  filter:    'SlidersHorizontal',
  sort:      'ArrowUpDown',
  export:    'Download',
  import:    'Upload',
  print:     'Printer',
  refresh:   'RefreshCw',
  copy:      'Copy',
  share:     'Share2',
  void:      'Ban',
  confirm:   'CheckCircle',
  back:      'ArrowLeft',
  forward:   'ArrowRight',
  expand:    'ChevronDown',
  collapse:  'ChevronUp',
  restock:   'PackagePlus',
  drag:      'GripVertical',
  invite:    'UserPlus',
  removeUser:'UserMinus',

  // Status
  alert:      'Bell',
  alertActive:'BellDot',
  warning:    'AlertTriangle',
  error:      'AlertCircle',
  success:    'CheckCircle2',
  info:       'Info',
  lowStock:   'TrendingDown',
  outOfStock: 'PackageX',
  inStock:    'PackageCheck',

  // Financial
  cash:     'Banknote',
  credit:   'CreditCard',
  transfer: 'ArrowLeftRight',
  revenue:  'TrendingUp',
  profit:   'DollarSign',
  tax:      'Percent',
  discount: 'Tag',
  receipt:  'Receipt',

  // Users
  user:     'User',
  owner:    'Crown',
  manager:  'ShieldCheck',
  cashier:  'UserCheck',
  login:    'LogIn',
  logout:   'LogOut',
  password: 'Lock',
  email:    'Mail',
  phone:    'Phone',
  avatar:   'CircleUser',

  // Shop
  shop:        'Store',
  theme:       'Palette',
  darkMode:    'Moon',
  lightMode:   'Sun',
  systemMode:  'Monitor',
  currency:    'CircleDollarSign',
  timezone:    'Clock',
  language:    'Globe',
  notifications:'Bell',
  permissions: 'ShieldHalf',
  location:    'MapPin',
  website:     'Link',

  // Categories
  skincare:    'Sparkles',
  makeup:      'Wand2',
  haircare:    'Scissors',
  fragrance:   'Wind',
  bodycare:    'Droplets',
  nails:       'Brush',
  wellness:    'Heart',
  accessories: 'Watch',
  tools:       'Wrench',
  supplements: 'Pill',
  clothing:    'Shirt',
  food:        'ShoppingBag',
  electronics: 'Zap',
  home:        'Home',
  books:       'BookOpen',
  sports:      'Dumbbell',
  toys:        'Gamepad2',
  art:         'PaintBucket',
  medical:     'Stethoscope',
  automotive:  'Car',
  garden:      'Flower2',
  pets:        'PawPrint',
  gifts:       'Gift',
  jewelry:     'Diamond',
} as const;

export type IconKey = keyof typeof ICONS;
export type IconName = typeof ICONS[IconKey];

export const CATEGORY_ICON_KEYS: IconKey[] = [
  'skincare','makeup','haircare','fragrance','bodycare','nails',
  'wellness','accessories','tools','supplements','clothing','food',
  'electronics','home','books','sports','toys','art','medical',
  'automotive','garden','pets','gifts','jewelry',
];
